### ISSUE TITLE
Prepare webserver to connect to the MySQL Database

### ISSUE THREAD

**Issue by pgbezerra** [pgbezerra-org/legendary-guacamole#6]
We need to make the `webserver` communicate with the database.
You should do a `SELECT 1` to prove it works and print the result in the index view.

# Rules

- The database changes must be applied with migrations
- You have to use the entity framework

# Documents

https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework-core-example.html
https://learn.microsoft.com/en-us/ef/

**Comment by MatthewLacerda2** [comment]
![SELECT 1](https://user-images.githubusercontent.com/25264421/235832521-1916a0fb-42f4-4626-83dc-967f7d155c2d.png)

SQL Server Studio 19

**Comment by pgbezerra** [comment]
Great! Let's see this merged!
